import type { LevelDef } from "@/engine/types";
import { LEVEL_FILES } from "./manifest";
import { parseLevel } from "./parse";

/**
 * The bundled levels, in play order. Levels 1-30 are hand authored; 31 and up
 * are generated (DESIGN.md 4). Every one of them passes the gate in
 * `tools/validate-levels.ts` before it ships. The manifest is generated by
 * `npm run levels:manifest`, and CI fails if it is stale.
 */
export const LEVELS: LevelDef[] = LEVEL_FILES.map(parseLevel);

export function levelById(id: number): LevelDef | undefined {
  return LEVELS.find((level) => level.id === id);
}

export function nextLevelId(id: number): number | null {
  const index = LEVELS.findIndex((level) => level.id === id);
  const next = index === -1 ? undefined : LEVELS[index + 1];
  return next ? next.id : null;
}
