// Generated by `npm run levels:manifest`. Do not edit by hand.
import type { RawLevel } from "./parse";
import level001 from "./data/001.json";
import level002 from "./data/002.json";
import level003 from "./data/003.json";
import level004 from "./data/004.json";
import level005 from "./data/005.json";
import level006 from "./data/006.json";
import level007 from "./data/007.json";
import level008 from "./data/008.json";
import level009 from "./data/009.json";
import level010 from "./data/010.json";
import level011 from "./data/011.json";
import level012 from "./data/012.json";
import level013 from "./data/013.json";
import level014 from "./data/014.json";
import level015 from "./data/015.json";
import level016 from "./data/016.json";
import level017 from "./data/017.json";
import level018 from "./data/018.json";
import level019 from "./data/019.json";
import level020 from "./data/020.json";
import level021 from "./data/021.json";
import level022 from "./data/022.json";
import level023 from "./data/023.json";
import level024 from "./data/024.json";
import level025 from "./data/025.json";
import level026 from "./data/026.json";
import level027 from "./data/027.json";
import level028 from "./data/028.json";
import level029 from "./data/029.json";
import level030 from "./data/030.json";

/** Every level JSON in the bundle, in play order. */
export const LEVEL_FILES: RawLevel[] = [
  level001 as RawLevel,
  level002 as RawLevel,
  level003 as RawLevel,
  level004 as RawLevel,
  level005 as RawLevel,
  level006 as RawLevel,
  level007 as RawLevel,
  level008 as RawLevel,
  level009 as RawLevel,
  level010 as RawLevel,
  level011 as RawLevel,
  level012 as RawLevel,
  level013 as RawLevel,
  level014 as RawLevel,
  level015 as RawLevel,
  level016 as RawLevel,
  level017 as RawLevel,
  level018 as RawLevel,
  level019 as RawLevel,
  level020 as RawLevel,
  level021 as RawLevel,
  level022 as RawLevel,
  level023 as RawLevel,
  level024 as RawLevel,
  level025 as RawLevel,
  level026 as RawLevel,
  level027 as RawLevel,
  level028 as RawLevel,
  level029 as RawLevel,
  level030 as RawLevel,
];
