// Generated by `npm run levels:manifest`. Do not edit by hand.
import type { RawLevel } from "./parse";
import level001 from "./data/001.json";
import level002 from "./data/002.json";
import level003 from "./data/003.json";
import level004 from "./data/004.json";
import level005 from "./data/005.json";
import level006 from "./data/006.json";
import level007 from "./data/007.json";
import level008 from "./data/008.json";
import level009 from "./data/009.json";
import level010 from "./data/010.json";
import level011 from "./data/011.json";
import level012 from "./data/012.json";
import level013 from "./data/013.json";
import level014 from "./data/014.json";
import level015 from "./data/015.json";
import level016 from "./data/016.json";
import level017 from "./data/017.json";
import level018 from "./data/018.json";
import level019 from "./data/019.json";
import level020 from "./data/020.json";
import level021 from "./data/021.json";
import level022 from "./data/022.json";
import level023 from "./data/023.json";
import level024 from "./data/024.json";
import level025 from "./data/025.json";
import level026 from "./data/026.json";
import level027 from "./data/027.json";
import level028 from "./data/028.json";
import level029 from "./data/029.json";
import level030 from "./data/030.json";
import level031 from "./data/031.json";
import level032 from "./data/032.json";
import level033 from "./data/033.json";
import level034 from "./data/034.json";
import level035 from "./data/035.json";
import level036 from "./data/036.json";
import level037 from "./data/037.json";
import level038 from "./data/038.json";
import level039 from "./data/039.json";
import level040 from "./data/040.json";
import level041 from "./data/041.json";
import level042 from "./data/042.json";
import level043 from "./data/043.json";
import level044 from "./data/044.json";
import level045 from "./data/045.json";
import level046 from "./data/046.json";
import level047 from "./data/047.json";
import level048 from "./data/048.json";
import level049 from "./data/049.json";
import level050 from "./data/050.json";
import level051 from "./data/051.json";
import level052 from "./data/052.json";
import level053 from "./data/053.json";
import level054 from "./data/054.json";
import level055 from "./data/055.json";
import level056 from "./data/056.json";
import level057 from "./data/057.json";
import level058 from "./data/058.json";
import level059 from "./data/059.json";
import level060 from "./data/060.json";
import level061 from "./data/061.json";
import level062 from "./data/062.json";
import level063 from "./data/063.json";
import level064 from "./data/064.json";
import level065 from "./data/065.json";
import level066 from "./data/066.json";
import level067 from "./data/067.json";
import level068 from "./data/068.json";
import level069 from "./data/069.json";
import level070 from "./data/070.json";
import level071 from "./data/071.json";
import level072 from "./data/072.json";
import level073 from "./data/073.json";
import level074 from "./data/074.json";
import level075 from "./data/075.json";
import level076 from "./data/076.json";
import level077 from "./data/077.json";
import level078 from "./data/078.json";
import level079 from "./data/079.json";
import level080 from "./data/080.json";

/** Every level JSON in the bundle, in play order. */
export const LEVEL_FILES: RawLevel[] = [
  level001 as RawLevel,
  level002 as RawLevel,
  level003 as RawLevel,
  level004 as RawLevel,
  level005 as RawLevel,
  level006 as RawLevel,
  level007 as RawLevel,
  level008 as RawLevel,
  level009 as RawLevel,
  level010 as RawLevel,
  level011 as RawLevel,
  level012 as RawLevel,
  level013 as RawLevel,
  level014 as RawLevel,
  level015 as RawLevel,
  level016 as RawLevel,
  level017 as RawLevel,
  level018 as RawLevel,
  level019 as RawLevel,
  level020 as RawLevel,
  level021 as RawLevel,
  level022 as RawLevel,
  level023 as RawLevel,
  level024 as RawLevel,
  level025 as RawLevel,
  level026 as RawLevel,
  level027 as RawLevel,
  level028 as RawLevel,
  level029 as RawLevel,
  level030 as RawLevel,
  level031 as RawLevel,
  level032 as RawLevel,
  level033 as RawLevel,
  level034 as RawLevel,
  level035 as RawLevel,
  level036 as RawLevel,
  level037 as RawLevel,
  level038 as RawLevel,
  level039 as RawLevel,
  level040 as RawLevel,
  level041 as RawLevel,
  level042 as RawLevel,
  level043 as RawLevel,
  level044 as RawLevel,
  level045 as RawLevel,
  level046 as RawLevel,
  level047 as RawLevel,
  level048 as RawLevel,
  level049 as RawLevel,
  level050 as RawLevel,
  level051 as RawLevel,
  level052 as RawLevel,
  level053 as RawLevel,
  level054 as RawLevel,
  level055 as RawLevel,
  level056 as RawLevel,
  level057 as RawLevel,
  level058 as RawLevel,
  level059 as RawLevel,
  level060 as RawLevel,
  level061 as RawLevel,
  level062 as RawLevel,
  level063 as RawLevel,
  level064 as RawLevel,
  level065 as RawLevel,
  level066 as RawLevel,
  level067 as RawLevel,
  level068 as RawLevel,
  level069 as RawLevel,
  level070 as RawLevel,
  level071 as RawLevel,
  level072 as RawLevel,
  level073 as RawLevel,
  level074 as RawLevel,
  level075 as RawLevel,
  level076 as RawLevel,
  level077 as RawLevel,
  level078 as RawLevel,
  level079 as RawLevel,
  level080 as RawLevel,
];
