#!/usr/bin/env tsx
/**
 * Writes `src/levels/manifest.ts` from whatever level JSON is in
 * `src/levels/data`. Thirty hand-authored files are thirty import lines, and a
 * hand-maintained list is the kind of thing that silently drops a level.
 *
 *   npm run levels:manifest           rewrite the manifest
 *   npm run levels:manifest -- --check   fail if it is out of date (CI.md 2.2)
 */
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { loadLevels } from "./levels";

const MANIFEST = join(process.cwd(), "src", "levels", "manifest.ts");

function render(files: string[]): string {
  const names = files.map((file) => `level${file.replace(".json", "")}`);
  const imports = names
    .map((name, index) => `import ${name} from "./data/${files[index]!}";`)
    .join("\n");

  return `// Generated by \`npm run levels:manifest\`. Do not edit by hand.
import type { RawLevel } from "./parse";
${imports}

/** Every level JSON in the bundle, in play order. */
export const LEVEL_FILES: RawLevel[] = [
${names.map((name) => `  ${name} as RawLevel,`).join("\n")}
];
`;
}

async function main(): Promise<void> {
  const levels = await loadLevels();
  const wanted = render(levels.map((entry) => entry.file));

  if (process.argv.includes("--check")) {
    const current = await readFile(MANIFEST, "utf8").catch(() => "");
    if (current.replace(/\r\n/g, "\n") === wanted) {
      console.log(`levels:manifest — up to date, ${levels.length} level(s)`);
      return;
    }
    console.error("levels:manifest — out of date; run `npm run levels:manifest`");
    process.exit(1);
  }

  await writeFile(MANIFEST, wanted, "utf8");
  console.log(`levels:manifest — wrote ${levels.length} level(s)`);
}

await main();
